<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "blog_erar"
 *
 * Auto generated by Extension Builder 2016-01-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Blog_Eraud-Arabe',
	'description' => '',
	'category' => 'plugin',
	'author' => 'André RABE, Evelyne RAUD',
	'author_email' => 'andre.k.rabe@gmail.com, evelyne.raud@gmail.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);